### PR TITLE
Allow building with haskell-gi-base-0.25

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by ocharles** [comment]
Could we also get a new release/revision with this change? I'm happy to help if you want a co-maintainer!

**Comment by ocharles** [comment]
Thanks @mr ! Would you mind also uploading a new release to Hackage? Thanks :smiley:

**Comment by mr** [comment]
I will as soon as I can. I'm a bit busy lately and need to find a machine I can actually do the build on.

**Comment by ocharles** [comment]
That's perfectly reasonable! As we (@CircuitHub) use this in production, I'm also more than happy to help out (e.g., release to Hackage on your behalf) - it seems unfair we get all of this for free. So if you need anything, just let me know :v:

**Pull request merged**
